//
// Created by yuanxuedong on 2023/10/21.
//

#ifndef CPP_DESIGNPATTERN_DEPENDENCY_REVERSE_PRINCIPLE_MAIN_H
#define CPP_DESIGNPATTERN_DEPENDENCY_REVERSE_PRINCIPLE_MAIN_H


class dependency_reverse_principle_main {

};


#endif //CPP_DESIGNPATTERN_DEPENDENCY_REVERSE_PRINCIPLE_MAIN_H
