//
// Created by yuanxuedong on 2023/10/21.
//

#ifndef CPP_DESIGNPATTERN_ABSTRACT_FACTORY_PATTERN_MAIN_H
#define CPP_DESIGNPATTERN_ABSTRACT_FACTORY_PATTERN_MAIN_H


class abstract_factory_pattern_main {

};


#endif //CPP_DESIGNPATTERN_ABSTRACT_FACTORY_PATTERN_MAIN_H
